name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  build-and-deploy:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy to docs
        run: |
          rm -rf docs
          mv build docs
          cp docs/index.html docs/404.html
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add docs
          git commit -m "chore: deploy to docs"
          git push origin main 